name: Jsonnet

on:
  push:
    branches: [ main ]
    paths:
      - 'deploy/**'
      - '*.jsonnet'
      - '*.libsonnet'
  pull_request:
    branches: [ main ]
    paths:
      - 'deploy/**'
      - '*.jsonnet'
      - '*.libsonnet'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Set up Jsonnet
        run: ./env-jsonnet.sh

      - name: Generate
        run: cd deploy && make --always-make vendor manifests

      - name: Archive generatated manifests
        uses: actions/upload-artifact@v3
        with:
          name: manifests
          path: |
            deploy/manifests
